# This is a config for E2B sandbox template.
# You can use template ID (gxv8u16jowq2vqqqxyq1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("gxv8u16jowq2vqqqxyq1") # Sync sandbox
# sandbox = await AsyncSandbox.create("gxv8u16jowq2vqqqxyq1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('gxv8u16jowq2vqqqxyq1')

team_id = "c9504189-ebfa-4ca1-aba5-b7aa8947221c"
start_cmd = "/home/user/start.sh"
dockerfile = "e2b.Dockerfile"
template_id = "gxv8u16jowq2vqqqxyq1"
